server:
  port: 9003

spring:
  application:
    name: springcloud-alibaba-payment-service
  cloud:
    nacos:
      discovery:
         server-addr: 192.168.1.254:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'