server:
  port: 91

spring:
  application:
    name: springcloud-alibaba-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.254:8848
    sentinel:
      transport:
        dashboard: 192.168.1.254:8080
        port: 8719

# 消费者 消费的微服务名称
service-url:
  nacos-service: http://springcloud-alibaba-payment-service
