server:
  port: 84

spring:
  application:
    name: springcloud-order-service
  cloud:
    consul:
      # Consul 服务器的ip和端口
      host: 192.168.1.254
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # Spring Boot 服务的主机地址
        hostname: 192.168.100.9