server:
  port: 8401

spring:
  application:
    name: springcloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
         server-addr: 192.168.1.254:8848
    sentinel:
      transport:
        dashboard: 192.168.1.254:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.254:8848
            dataId: springcloud-alibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'