server:
  port: 9002

spring:
  application:
    name: springcloud-alibaba-payment-service
  cloud:
    nacos:
      discovery:
        # server-addr: 192.168.1.254:8848
        server-addr: 192.168.1.254:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'