server:
  port: 8002

spring:
  application:
    name: springcloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.112.124.165:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.cloudfly.springcloud.pojo

eureka:
  client:
    # 将本服务注册进 eureka Server
    register-with-eureka: true
    # 是否从 eureka Server 获得已有注册信息
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    # 服务名称
    instance-id: payment8002
    # 访问路径显示IP地址
    prefer-ip-address: true