server:
  port: 86

spring:
  application:
    name: springcloud-order-service

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka, http://eureka7002:7002/eureka

ribbon:
  # 建立连接所用的时间
  ReadTimeout:  5000
  # 建立连接后 从服务器读取到可用资源的时间
  ConnectTimeout: 5000

logging:
  level:
    # Feign 以什么级别监控哪个接口
    com.cloudfly.springcloud.service.PaymentFeignService: debug



