server:
  port: 80

spring:
  application:
    name: springcloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  # 采样率介于 0 到 1 之间， 1表示全部采集

eureka:
  client:
    # 将本服务注册进 eureka Server
    register-with-eureka: true
    # 是否从 eureka Server 获得已有注册信息
    fetchRegistry: true
    service-url:
#      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
      defaultZone: http://localhost:7001/eureka